//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCalendarDate, NSString;

@interface Alarm : NSObject
{
    unsigned int _alarmHour;
    unsigned int _alarmMinute;
    int _alarmSetting;
    NSString *_alarmSoundIdentifier;
    NSString *_alarmTitle;
    NSCalendarDate *_snoozeUntilDate;
    unsigned int _isActive:1;
    unsigned int _repeats:1;
    unsigned int _allowsSnooze:1;
    unsigned int _dontSendUpdate:1;
    unsigned int _dontStopSnoozing:1;
    unsigned int _reserved:27;
}

- (id)description;
- (void)_update;
- (id)init;
- (id)_initWithDictionary:(id)arg1;
- (id)_prefsDictionary;
- (void)dealloc;
- (BOOL)alarmTimesEqualTo:(id)arg1;
- (void)setAlarmHour:(unsigned int)arg1 minute:(unsigned int)arg2;
- (void)getAlarmHour:(unsigned int *)arg1 minute:(unsigned int *)arg2;
- (id)_fireDateAfterDate:(id)arg1;
- (void)setActive:(BOOL)arg1;
- (BOOL)isActive;
- (void)setRepeats:(BOOL)arg1;
- (BOOL)repeats;
- (void)setDaySetting:(int)arg1;
- (int)daySetting;
- (void)setAllowsSnooze:(BOOL)arg1;
- (BOOL)allowsSnooze;
- (BOOL)isSnoozing;
- (void)startSnoozingFromDate:(id)arg1;
- (void)stopSnoozing;
- (id)_snoozeUntilDate;
- (void)setAlarmSoundIdentifier:(id)arg1;
- (id)alarmSoundIdentifier;
- (void)setAlarmTitle:(id)arg1;
- (id)alarmTitle;
- (void)_activeAlertItem;
- (void)fireAlarm;

@end

