//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, NSTimer;

@interface AlarmController : NSObject
{
    NSMutableArray *_alarmList;
    NSTimer *_alarmTimer;
    NSMutableArray *_alarmsToFire;
    unsigned int _readingPrefs:1;
    NSTimer *_countDownTimer;
    double _countDownTimerInterval;
    NSString *_countDownTimerSoundIdentifier;
    struct __CFDate *_alarmWakeupDate;
    struct __CFDate *_countdownWakeupDate;
}

+ (id)sharedAlarmController;
- (void)_readPreferences;
- (void)_savePreferences;
- (void)_alarmChanged:(id)arg1;
- (id)init;
- (void)dealloc;
- (unsigned int)addAlarm:(id)arg1;
- (void)removeAlarmAtIndex:(unsigned int)arg1;
- (id)alarms;
- (void)_scheduleAlarms;
- (void)_alarmTimeReached:(id)arg1;
- (void)setCountDownTimerInterval:(double)arg1 withSoundIdentifier:(id)arg2;
- (void)_countDownTimerFired:(id)arg1;
- (void)_sleepTimerFired:(id)arg1;
- (double)countDownTimerInterval;
- (id)countDownTimerSoundIdentifier;
- (void)_wokeFromSleep;

@end

