//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPushButton.h"

@interface BorderedPushButton : UIPushButton
{
}

- (void)_sizeToFit;
- (void)drawButtonPart:(int)arg1 inRect:(struct CGRect)arg2;

@end

