//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface EllipseWindow : UIWindow
{
    BOOL showEcho;
    BOOL inUse;
    BOOL isAnimating;
    struct CGPoint startLoc;
    double startTime;
}

+ (void)initialize;
+ (struct CGRect)constrainFrameToScreen:(struct CGRect)arg1;
- (void)fixupOrdering;
- (void)playTouchAnimation;
- (BOOL)isHidden;
- (void)setHidden:(BOOL)arg1;
- (void)finishHide;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)showTouchImage:(BOOL)arg1;

@end

