//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDismissOnlyAlertItem.h"

@interface SBActivationInfoAlertItem : SBDismissOnlyAlertItem
{
}

+ (id)activeItem;
- (BOOL)willShowInAwayItems;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)willActivate;
- (void)didDeactivate:(BOOL)arg1;

@end

