//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary;

@interface SBAccessoryController : NSObject
{
    NSDictionary *_lingoToApplicationMap;
    NSMutableDictionary *_availableAccessories;
}

+ (id)sharedAccessoryController;
- (id)init;
- (void)dealloc;
- (void)reloadLingoToApplicationMap;
- (void)_enableAccessoryIfNeeded:(id)arg1 forLingo:(int)arg2;
- (void)_disableAccessoryIfNeeded:(id)arg1 forLingo:(int)arg2;
- (void)accessoryAvailabilityChanged:(int)arg1 availability:(int)arg2;

@end

