//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface SBAlertItemsController : NSObject
{
    NSMutableArray *_lockedAlertItems;
    NSMutableArray *_unlockedAlertItems;
    NSTimer *_autoDismissTimer;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)convertAnimatingUnlockedAlertsToLockedAlerts;
- (void)deactivateAllAlertItems;
- (void)resetAutoDismissTimer;
- (void)activateAlertItem:(id)arg1;
- (void)_deactivateAlertItem:(id)arg1 forLock:(BOOL)arg2;
- (void)deactivateAlertItem:(id)arg1;
- (void)autoDismissAlertItem:(id)arg1;
- (BOOL)isShowingAlerts;
- (BOOL)deactivateAlertForMenuClick;
- (void)deactivateAlertItemsForLock;

@end

