//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBRingingAlertItem.h"

@class Alarm;

@interface SBAlarmAlertItem : SBRingingAlertItem
{
    Alarm *_alarm;
    BOOL _snoozeAlarm;
}

- (id)initWithAlarm:(id)arg1;
- (void)dealloc;
- (void)setAlarm:(id)arg1;
- (id)alarm;
- (BOOL)allowsSnooze;
- (void)startSnoozingAndDeactivate;
- (id)lockLabel;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)soundIdentifier;
- (id)avClientName;
- (id)avAudioCategory;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;

@end

