//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIAlertSheet;

@interface SBAlertItem : NSObject
{
    UIAlertSheet *_alertSheet;
    BOOL _disallowUnlockAction;
    BOOL _orderOverSBAlert;
}

- (id)alertSheet;
- (void)dealloc;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)shouldShowInLockScreen;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)undimsScreen;
- (BOOL)dismissOnLock;
- (BOOL)willShowInAwayItems;
- (void)cleanPreviousConfiguration;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (float)lockLabelFontSize;
- (double)autoDismissInterval;
- (void)setDisallowsUnlockAction:(BOOL)arg1;
- (BOOL)disallowsUnlockAction;
- (void)performUnlockAction;
- (void)setOrderOverSBAlert:(BOOL)arg1;
- (void)willActivate;
- (void)didActivate;
- (void)willDeactivate:(BOOL)arg1;
- (void)didDeactivate:(BOOL)arg1;
- (id)awayItem;

@end

