//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBAlert;

@interface SBAlertDisplay : UIView
{
    SBAlert *_alert;
    unsigned int _displaysAboveStatusBar:1;
    unsigned int _shouldAnimateIn:1;
}

- (void)setAlert:(id)arg1;
- (id)alert;
- (void)launchURL:(id)arg1;
- (void)willDismiss;
- (void)dismiss;
- (void)setHandlerAlreadyActive:(BOOL)arg1;
- (void)alertDisplayWillBecomeVisible;
- (void)alertDisplayBecameVisible;
- (BOOL)displaysAboveStatusBar;
- (void)setDisplaysAboveStatusBar:(BOOL)arg1;
- (BOOL)isReadyToBeRemovedFromView;
- (void)setShouldAnimateIn:(BOOL)arg1;
- (BOOL)shouldAnimateIn;

@end

