//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIKeyboard, UINavigationBar, UIScroller, UITextField;

@interface SBAlertInputView : SBSlidingAlertDisplay
{
    UITextField *_inputTextField;
    UIKeyboard *_keyboard;
    SBTextDisplayView *_textDisplay;
    UIScroller *_scroller;
    UINavigationBar *_bar;
    BOOL _digitsOnly;
    id _delegate;
    int _minLength;
    int _maxLength;
}

+ (id)createTopBarForInstance:(id)arg1;
+ (id)createBottomBarForInstance:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)showsDesktopImage;
- (void)setMiddleContentAlpha:(float)arg1;
- (void)setText:(id)arg1;
- (void)alertDisplayWillBecomeVisible;
- (void)setMinLength:(int)arg1;
- (void)setMaxLength:(int)arg1;
- (void)_setNavigationBar:(id)arg1;
- (void)_setInputTextField:(id)arg1;
- (void)_setKeyboard:(id)arg1;
- (BOOL)textField:(id)arg1 shouldInsertText:(id)arg2 replacingRange:(struct _NSRange)arg3;
- (void)setDigitsOnly:(BOOL)arg1;
- (void)sbAlertInputViewSendClicked:(id)arg1;
- (void)sbAlertInputViewCancelClicked:(id)arg1;
- (id)textField;
- (void)_sendClicked:(id)arg1;

@end

