//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface SBApplicationIconBadge : UIView
{
    NSString *_badge;
    struct CGSize _badgeContentSize;
}

- (id)initWithBadge:(id)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;

@end

