//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDisplay.h"

@class NSMutableArray, NSMutableSet, NSString, UIRemoteApplication;

@interface SBApplication : SBDisplay
{
    NSString *_roleID;
    NSString *_path;
    NSString *_bundleID;
    BOOL _isLaunching;
    int _failedLaunchCount;
    int _memoryWarningCount;
    BOOL _enabled;
    BOOL _useDemoRole;
    unsigned int _dataUsage:3;
    NSString *_demoRole;
    NSMutableSet *_statusBarItemSet;
    NSMutableArray *_tags;
    UIRemoteApplication *_remoteApplication;
    struct __CFSet *_launchAlerts;
    int _pid;
}

+ (id)applicationWithPath:(id)arg1;
+ (id)applicationWithPath:(id)arg1 roleID:(id)arg2;
+ (id)applicationWithPath:(id)arg1 roleID:(id)arg2 plist:(id)arg3;
+ (id)applicationWithDisplayIdentifier:(id)arg1;
+ (id)springBoard;
+ (id)iPod;
+ (void)setUseDemoRole:(BOOL)arg1;
+ (void)flushSnapshotsForIdentifier:(id)arg1;
+ (void)flushLaunchAlertsOfType:(int)arg1;
- (id)init;
- (id)description;
- (void)_startLaunchWatchdogTimer;
- (void)_startResumeWatchdogTimer;
- (void)_startDeactivationWatchdogTimer;
- (void)_cancelWatchdogTimer;
- (void)dealloc;
- (void)setRoleID:(id)arg1;
- (id)roleID;
- (BOOL)enabled;
- (void)setEnabled:(BOOL)arg1;
- (id)demoRole;
- (void)setDemoRole:(id)arg1;
- (void)setUseDemoRole:(BOOL)arg1;
- (id)path;
- (id)bundleID;
- (id)bundle;
- (id)bundleForLaunching;
- (id)arguments;
- (void)setTags:(id)arg1;
- (id)tags;
- (unsigned int)dataUsage;
- (BOOL)isWidget;
- (id)_additionalDisplayQualification;
- (id)displayIdentifier;
- (id)pathForIcon;
- (BOOL)shouldLaunchPNGless;
- (id)pathForDefaultImage:(char *)arg1;
- (id)displayName;
- (id)launchURLArgument;
- (void)_sendCurrentDeviceOrientation;
- (BOOL)activate;
- (BOOL)deactivate;
- (void)watchdogForDeactivate;
- (void)watchdogForResume;
- (void)watchdogForLaunch;
- (void)deactivated;
- (BOOL)kill;
- (void)_autoLaunchMailIfNeeded;
- (void)exitedAbnormally;
- (void)exitedNormally;
- (unsigned int)priority;
- (int)failedLaunchCount;
- (void)removeAppPrefs;
- (void)launchFailed;
- (void)launchSucceeded;
- (int)PID;
- (void)setPID:(int)arg1;
- (int)memoryWarningCount;
- (void)setMemoryWarningCount:(id)arg1;
- (void)noteAddedStatusBarItem:(id)arg1;
- (void)noteRemovedStatusBarItem:(id)arg1;
- (id)remoteApplication;
- (BOOL)showLaunchAlertForType:(int)arg1;
- (void)resetLaunchAlertForType:(int)arg1;
- (BOOL)isRunning;

@end

