//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface SBApplicationIconLabel : UIView
{
    NSString *_label;
}

- (id)initWithSize:(struct CGSize)arg1 label:(id)arg2;
- (void)dealloc;
- (void)drawLabelInRect:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

