//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

@class NSDate, NSDictionary, NSMutableArray, NSTimer, SBAlertItem, SBAwayItem, SBAwayModel, SBAwayView, SBSlidingAlertDisplay, SBUIController;

@interface SBAwayController : SBAlert
{
    SBUIController *_uiController;
    SBAwayModel *_model;
    SBAwayView *_awayView;
    NSTimer *_dimTimer;
    NSDate *_lockDate;
    SBAwayItem *_clickedItem;
    unsigned int _isLocked:1;
    unsigned int _isDimmed:1;
    unsigned int _isDimming:1;
    unsigned int _orderedOutDimmed:1;
    unsigned int _frontDimmed:1;
    unsigned int _isBlocked:1;
    unsigned int _makingEmergencyCall:1;
    unsigned int _appRequestedPasscodeEntry:1;
    unsigned int _needToMakeEmergencyCall:1;
    unsigned int _isSyncing:1;
    unsigned int _relockAfterUnlock:1;
    unsigned int _wasLockedBeforeSync:1;
    unsigned int _wasDeviceLockedBeforeSync:1;
    NSDictionary *_nowPlayingInfo;
    double _sleepDelay;
    SBSlidingAlertDisplay *_deviceUnlockDisplay;
    double _deviceLockBlockTime;
    double _deviceLockGracePeriodEndTimeInterval;
    NSMutableArray *_pendingAlertItems;
    SBAlertItem *_currentAlertItem;
    int _notifyLockStateToken;
    int _notifyDontAnimateREOToken;
}

+ (id)sharedAwayController;
+ (void)registerForAlerts;
- (id)initWithUIController:(id)arg1;
- (id)awayModel;
- (void)applicationDidFinishLaunching:(id)arg1;
- (struct CGRect)alertWindowRect;
- (float)finalAlpha;
- (BOOL)undimsDisplay;
- (id)awayView;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)alertDisplayWillBecomeVisible;
- (void)dealloc;
- (void)handleClickedItem:(id)arg1;
- (double)animateInDuration;
- (void)reactivatePendingAlertItems;
- (void)playLockSound;
- (void)_sendLockStateChangedNotification;
- (void)lock;
- (void)_unlockWithSound:(BOOL)arg1;
- (void)unlockWithSound:(BOOL)arg1;
- (void)unlockWithSound:(BOOL)arg1 alertDisplay:(id)arg2;
- (void)_timeChanged;
- (void)_setupDeviceLockGracePeriod;
- (BOOL)isPasswordProtected;
- (void)activationChanged:(id)arg1;
- (BOOL)_isDeviceBricked;
- (BOOL)isDeviceLocked;
- (void)setDeviceLocked:(BOOL)arg1;
- (void)applicationRequestedDeviceUnlock;
- (void)cancelApplicationRequestedDeviceLockEntry;
- (void)_clearBlockedState;
- (BOOL)isBlocked;
- (BOOL)isPermanentlyBlocked:(double *)arg1;
- (void)noteSyncStateChanged;
- (BOOL)isSyncing;
- (void)noteResetRestoreStateChanged;
- (BOOL)isLocked;
- (void)lockBarStartedTracking:(id)arg1;
- (void)lockBarStoppedTracking:(id)arg1;
- (void)resetAwayItems;
- (void)frontLockedAnimationFinished;
- (void)_frontForSuspendedLockAfterDelay;
- (void)frontForSuspendedLockAfterDelay:(float)arg1;
- (BOOL)shouldAnimateOthersSuspension;
- (void)frontLocked:(BOOL)arg1 animate:(BOOL)arg2 automatically:(BOOL)arg3;
- (void)attemptUnlock;
- (BOOL)isAttemptingUnlock;
- (void)_finishedUnlockAttemptWithStatus:(BOOL)arg1;
- (BOOL)attemptDeviceUnlockWithPassword:(id)arg1 alertDisplay:(id)arg2;
- (void)sleep;
- (void)preventIdleSleep;
- (void)wake;
- (void)cancelDimTimer;
- (void)restartDimTimer:(float)arg1;
- (BOOL)isDimmed;
- (BOOL)moveAlertItemToAwayView:(id)arg1;
- (void)clensePendingQueueOfAwayItems;
- (void)relock;
- (void)relockDimmed:(BOOL)arg1;
- (double)sleepDelay;
- (void)delaySleepByNumberOfSeconds:(float)arg1;
- (void)dimScreen:(BOOL)arg1;
- (void)_undimScreen;
- (void)undimScreen;
- (void)activate;
- (BOOL)deactivate;
- (BOOL)allowsStackingOfAlert:(id)arg1;
- (BOOL)allowsInCallStatusBar;
- (int)statusBarMode;
- (BOOL)animatesDismissal;
- (void)orderOut;
- (void)didFinishAnimatingOut;
- (void)animator:(id)arg1 stopAnimation:(id)arg2;
- (void)clickItem:(id)arg1;
- (void)updateNowPlayingInfo:(id)arg1;
- (void)handleRequestedAlbumArtBytes:(char *)arg1 length:(unsigned int)arg2;
- (void)updateClockFormat;
- (void)makeEmergencyCall;
- (void)_activateEmergencyCall;
- (void)emergencyCallWasDisplayed;
- (void)emergencyCallWasRemoved;
- (BOOL)isMakingEmergencyCall;
- (void)didAnimateLockKeypadIn;
- (void)didAnimateLockKeypadOut;
- (id)currentAlertItem;
- (void)pendOrDeactivateCurrentAlertItem;
- (BOOL)isCurrentAlertItemRinging;
- (BOOL)attemptSnoozeRingingAlertItem;
- (void)stopRingingAlertItem;
- (void)snoozeOrStopRingingAlertItem;
- (BOOL)trySnoozingAlarmAlertItem;
- (BOOL)activateAlertItem:(id)arg1;
- (BOOL)wantsToHandleAlert:(id)arg1;
- (void)deactivateAlertItem:(id)arg1;
- (void)updateInCallUI;
- (void)toggleShowsIMEIandICCID:(id)arg1;

@end

