//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, SBAwayController;

@interface SBAwayModel : NSObject
{
    SBAwayController *_controller;
    NSMutableArray *_standardVMs;
    NSMutableArray *_calls;
    NSMutableArray *_SMSs;
    NSMutableArray *_otherAwayItems;
}

- (id)initWithController:(id)arg1;
- (void)dealloc;
- (void)markAwayTime;
- (void)addOtherAwayItem:(id)arg1;
- (void)addCall:(struct __CTCall *)arg1;
- (void)addSMSMessage:(struct __CTSMSMessage *)arg1;
- (void)populateWithMissedCalls:(id)arg1;
- (void)populateWithMissedSMS:(id)arg1;
- (void)populateWithMissedEnhancedVoiceMails:(id)arg1;
- (id)missedItems;
- (int)uncoalescedMissedItemCount;
- (void)setStandardVoiceMailCount:(int)arg1;

@end

