//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSTimer, TPLCDView, UIImage;

@interface SBAwayInCallController : NSObject
{
    TPLCDView *_lcdView;
    BOOL _showsInCallInfo;
    NSTimer *_durationTimer;
    struct __CTCall *_displayedCall;
    NSString *_localizedLabel;
    UIImage *_callerImage;
    BOOL _isFullScreen;
}

- (id)initWithLCDView:(id)arg1;
- (void)dealloc;
- (id)callerImage;
- (BOOL)callerImageIsFullScreen;
- (void)fetchCallInformation:(id *)arg1 name:(id *)arg2 label:(id *)arg3 image:(id *)arg4 isFullScreen:(char *)arg5;
- (void)updateDuration;
- (void)reload;
- (void)setShowsInCallInfo:(BOOL)arg1;

@end

