//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSlidingAlertDisplay.h"

@class NSDictionary, NSString, NSTimer, SBAwayChargingView, SBAwayDateView, SBAwayInCallController, SBAwayItemsView, SBNowPlayingArtView, TPBottomButtonBar, TPBottomLockBar, UIAlertSheet, UIImage, UIPushButton;

@interface SBAwayView : SBSlidingAlertDisplay
{
    BOOL _isDimmed;
    BOOL _deferAwayItemFetching;
    BOOL _showingBlockedIndicator;
    SBAwayChargingView *_chargingView;
    SBAwayDateView *_dateView;
    SBNowPlayingArtView *_albumArtView;
    SBAwayItemsView *_awayItemsView;
    NSDictionary *_nowPlayingInfo;
    UIImage *_nowPlayingArt;
    NSString *_lastTrackArtPath;
    NSTimer *_blockedStatusUpdateTimer;
    UIAlertSheet *_alertSheet;
    SBAwayInCallController *_inCallController;
    TPBottomLockBar *_lockBar;
    TPBottomButtonBar *_cancelSyncBar;
    UIPushButton *_infoButton;
}

+ (id)createBottomBarForInstance:(id)arg1;
+ (id)lockLabel:(BOOL)arg1 fontSize:(float *)arg2;
- (void)_clearBlockedStatusUpdateTimer;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)postLockCompletedNotification:(BOOL)arg1;
- (void)dealloc;
- (void)_postLockCompletedNotification;
- (void)finishedAnimatingIn;
- (void)dismiss;
- (void)setBottomLockBar:(id)arg1;
- (BOOL)shouldAnimateIn;
- (void)startAnimations;
- (void)stopAnimations;
- (void)showInfoButton;
- (void)hideInfoButton;
- (void)updateInterface;
- (void)setMiddleContentAlpha:(float)arg1;
- (void)setDimmed:(BOOL)arg1;
- (void)setDrawsBlackBackground:(BOOL)arg1;
- (void)lockBarUnlocked:(id)arg1;
- (void)lockBarStartedTracking:(id)arg1;
- (void)lockBarStoppedTracking:(id)arg1;
- (void)updateLockBarLabel;
- (BOOL)shouldShowBlockedRedStatus;
- (void)_updateBlockedStatusLabel;
- (void)showBlockedStatus;
- (void)removeBlockedStatus;
- (void)_updateBlockedStatus;
- (id)dateView;
- (void)removeDateView;
- (void)addDateView;
- (id)inCallController;
- (BOOL)shouldShowInCallInfo;
- (void)updateInCallInfo;
- (void)_positionAwayItemsView;
- (void)hideAwayItems;
- (void)showAwayItems;
- (BOOL)hasAwayItems;
- (void)setShowingDeviceLock:(BOOL)arg1 duration:(float)arg2;
- (void)showAlertSheet:(id)arg1;
- (void)removeAlertSheet;
- (void)slideAlertSheetOut:(BOOL)arg1 direction:(BOOL)arg2 duration:(float)arg3;
- (void)_batteryStatusChanged:(id)arg1;
- (id)chargingView;
- (void)addChargingView;
- (void)hideChargingView;
- (void)showSyncingBottomBar:(BOOL)arg1;
- (void)hideSyncingBottomBar:(BOOL)arg1;
- (void)hideNowPlaying;
- (id)nowPlayingArtView;
- (void)musicPlayerDied:(id)arg1;
- (void)updateNowPlayingInfo:(id)arg1;
- (BOOL)updateNowPlayingArt;
- (void)handleRequestedAlbumArtBytes:(char *)arg1 length:(unsigned int)arg2;
- (void)animateToShowingDeviceLock:(BOOL)arg1;

@end

