//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, NSTimer, TPLCDTextView;

@interface SBAwayDateView : UIView
{
    NSTimer *_dateTimer;
    TPLCDTextView *_timeLabel;
    TPLCDTextView *_titleLabel;
    NSString *_title;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)labelWithFontSize:(float)arg1 origin:(struct CGPoint)arg2 fontName:(const char *)arg3;
- (id)labelWithFontSize:(float)arg1 origin:(struct CGPoint)arg2;
- (void)updateLabels;
- (void)updateClockFormat;
- (void)updateClock;
- (void)setTitle:(id)arg1;
- (void)removeFromSuperview;
- (void)movedToSuperview:(id)arg1;

@end

