//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBUIController;

@interface SBButtonBar : UIView
{
    SBUIController *_uiController;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)reload;
- (void)setUIController:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

