//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSString;

@interface SBCalendarAlertItem : SBAlertItem
{
    double _date;
    NSString *_title;
    NSString *_location;
    int _eventId;
}

+ (void)registerForAlerts;
+ (void)finishRegisteringForAlerts;
+ (void)alarmsDidFire:(id)arg1;
+ (void)alarmsDidSchedule:(id)arg1;
+ (void)significantTimeChange;
+ (void)didWakeFromSleep;
+ (void)adjustOnWake;
- (id)initWithDate:(double)arg1 title:(id)arg2 location:(id)arg3 eventId:(int)arg4;
- (void)dealloc;
- (id)_dateString:(BOOL)arg1;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (void)didPresentAlertSheet:(id)arg1;
- (void)revealEvent;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (void)performUnlockAction;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)willShowInAwayItems;
- (id)awayItem;

@end

