//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationIcon.h"

@class SBCalendarIconContentsView;

@interface SBCalendarApplicationIcon : SBApplicationIcon
{
    SBCalendarIconContentsView *_dateContents;
}

- (id)initWithApplication:(id)arg1;
- (void)dealloc;
- (void)setHighlighted:(BOOL)arg1;

@end

