//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet;

@interface SBDisplay : NSObject
{
    NSMutableDictionary *_activationValues;
    NSMutableDictionary *_deactivationValues;
    int _activationSettings;
    int _deactivationSettings;
    NSMutableSet *_suppressVolumeHudCategories;
    float _autoDimOverride;
    float _autoLockOverride;
    unsigned int _expectsFaceContact:1;
    unsigned int _disallowTouchPoints:1;
    unsigned int _accelerometerDeviceOrientationChangedEventsEnabled:1;
    unsigned int _accelerometerRawEventsEnabled:1;
    unsigned int _showsProgress:1;
}

+ (void)loadDisplayStates;
+ (void)saveDisplayStates;
+ (void)setDefaultValue:(id)arg1 forKey:(const id)arg2 displayIdentifier:(id)arg3;
+ (id)defaultValueForKey:(const id)arg1 displayIdentifier:(id)arg2;
+ (void)resetDefaultValuesForDisplayIdentifier:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)displayIdentifier;
- (void)clearActivationSettings;
- (void)setActivationSetting:(int)arg1 flag:(BOOL)arg2;
- (void)setActivationSetting:(int)arg1 value:(id)arg2;
- (id)activationValue:(int)arg1;
- (BOOL)activationSetting:(int)arg1;
- (void)clearDeactivationSettings;
- (void)setDeactivationSetting:(int)arg1 flag:(BOOL)arg2;
- (BOOL)deactivationSetting:(int)arg1;
- (void)setDeactivationSetting:(int)arg1 value:(id)arg2;
- (id)deactivationValue:(int)arg1;
- (BOOL)activate;
- (BOOL)deactivate;
- (void)deactivated;
- (BOOL)kill;
- (void)exitedAbnormally;
- (void)exitedNormally;
- (BOOL)allowsInCallStatusBar;
- (void)updateStatusBar:(float)arg1 fence:(int)arg2 animation:(int)arg3;
- (void)updateStatusBar:(float)arg1;
- (int)statusBarMode;
- (int)statusBarOrientation;
- (float)autoDimTime;
- (void)setAutoDimTime:(float)arg1;
- (float)autoLockTime;
- (void)setAutoLockTime:(float)arg1;
- (void)setExpectsFaceContact:(BOOL)arg1;
- (BOOL)expectsFaceContact;
- (void)setAccelerometerDeviceOrientationChangedEventsEnabled:(BOOL)arg1;
- (BOOL)accelerometerDeviceOrientationChangedEventsEnabled;
- (void)setAccelerometerRawEventsEnabled:(BOOL)arg1;
- (BOOL)accelerometerRawEventsEnabled;
- (void)setShowsProgress:(BOOL)arg1;
- (BOOL)showsProgress;
- (void)setSystemVolumeHUDEnabled:(BOOL)arg1 forCategory:(id)arg2;
- (BOOL)showSystemVolumeHUDForCategory:(id)arg1;
- (void)setTouchPointsAllowed:(BOOL)arg1;
- (BOOL)touchPointsAllowed;
- (id)description;
- (id)activationSettingsDescription;
- (id)deactivationSettingsDescription;

@end

