//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SBDisplayStack : NSObject
{
    NSMutableArray *_displayStack;
    CDUnknownFunctionPointerType _pushCallback;
    CDUnknownFunctionPointerType _popCallback;
}

- (id)init;
- (void)_setDisplayStack:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)setPushCallBack:(CDUnknownFunctionPointerType)arg1;
- (void)setPopCallBack:(CDUnknownFunctionPointerType)arg1;
- (BOOL)isEmpty;
- (void)pushDisplay:(id)arg1;
- (id)pop;
- (void)flushWithoutCallbackSparingDisplay:(id)arg1;
- (id)popDisplay:(id)arg1;
- (id)displays;
- (id)topDisplay;
- (id)topApplication;
- (id)topAlert;
- (id)description;

@end

