//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSString;

@interface SBDismissOnlyAlertItem : SBAlertItem
{
    NSString *_title;
    NSString *_body;
    double _autoDismissInterval;
    BOOL _hasDeactivated;
}

- (id)initWithTitle:(id)arg1 body:(id)arg2;
- (void)dealloc;
- (double)autoDismissInterval;
- (void)setAutoDismissInterval:(double)arg1;
- (void)setTitle:(id)arg1;
- (void)setBodyText:(id)arg1;
- (void)dismiss;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (void)performUnlockAction;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (void)didDeactivate:(BOOL)arg1;
- (BOOL)hasDeactivated;

@end

