//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPushButton.h"

@class NSString;

@interface SBEmergencyCallButton : UIPushButton
{
    NSString *_subtitle;
}

+ (struct __GSFont *)defaultFont;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setSubtitle:(id)arg1;
- (void)drawButtonPart:(int)arg1 inRect:(struct CGRect)arg2;

@end

