//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary, SBApplicationIcon, SBUIController, TPLCDTextView;

@interface SBIconList : UIView
{
    NSMutableDictionary *_allAppIcons;
    NSMutableArray *_displayedIcons;
    NSMutableDictionary *_accessoryIcons;
    NSMutableArray *_buttonBarIcons;
    NSMutableArray *_hiddenIconTags;
    NSMutableArray *_visibleIconTags;
    NSMutableArray *_duplicateIcons;
    SBUIController *_uiController;
    NSMutableArray *_accessoryIconsToAdd;
    NSMutableArray *_accessoryIconsToRemove;
    SBApplicationIcon *_pendingIcon;
    unsigned int _scattered:1;
    NSMutableDictionary *_displayDefinitions;
    TPLCDTextView *_idleText;
}

+ (id)sharedInstance;
- (id)initWithSize:(struct CGSize)arg1;
- (void)dealloc;
- (void)setUIController:(id)arg1;
- (void)setIdleModeText:(id)arg1;
- (void)lcdTextViewCompletedScroll:(id)arg1;
- (void)changeVisibilityOfIconsWithVisibleTags:(id)arg1 hiddenTags:(id)arg2;
- (BOOL)_shouldShowIcon:(id)arg1;
- (void)_addItemsToIconList:(id)arg1 fromPath:(id)arg2 withTags:(id)arg3;
- (void)loadAccessoryIcons;
- (id)displayOrder;
- (void)loadSectionDefinitions:(id)arg1 sectionIcons:(id)arg2 allIcons:(id)arg3;
- (void)iconVisibilityChanged;
- (void)loadAllIcons;
- (id)buttonBarIcons;
- (void)layoutIcons;
- (BOOL)isScattered;
- (void)scatter:(BOOL)arg1;
- (void)unscatter:(BOOL)arg1 startTime:(double)arg2;
- (void)stopAnimations;
- (void)attemptPendingLaunch;
- (BOOL)hasLaunchPending;
- (void)pendLaunchOfIcon:(id)arg1;
- (void)clickedIcon:(id)arg1;
- (id)applicationIconForQualfiedBundleID:(id)arg1;
- (struct CGPoint)originForIcon:(id)arg1;
- (void)showAccessoryAnimationDidStop:(id)arg1;
- (void)showAccessory:(id)arg1;
- (void)removeAccessoryAnimationDidStop:(id)arg1;
- (void)removeAccessory:(id)arg1;

@end

