//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIProgressIndicator, UIPushButton;

@interface SBInfoBubble : UIView
{
    NSString *_title;
    NSString *_string;
    struct CGRect _titleRect;
    struct CGRect _stringRect;
    UIPushButton *_backspace;
    UIProgressIndicator *_progressIndicator;
}

- (id)initWithTitle:(id)arg1 string:(id)arg2;
- (void)dealloc;
- (struct CGRect)_progressRect;
- (void)showProgressIndicator:(BOOL)arg1;
- (void)showBackspace:(BOOL)arg1;
- (void)highlight:(id)arg1;
- (void)unhighlight:(id)arg1;
- (void)backspace:(id)arg1;
- (void)resize;
- (void)setTitle:(id)arg1 string:(id)arg2;
- (id)title;
- (void)setTitle:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

