//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@interface SBLowPowerAlertItem : SBAlertItem
{
    unsigned int _talkMinutesLeft;
    unsigned int _talkLevel;
}

+ (id)systemVersionDescription;
+ (void)saveLowBatteryLog;
+ (void)savePowerDiagnosisLogWithCurrentCapacity:(int)arg1 startCapacity:(int)arg2;
+ (unsigned int)_thresholdForLevel:(unsigned int)arg1;
+ (BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned int)arg1;
+ (void)setBatteryLevel:(unsigned int)arg1;
- (id)initWithTalkTimeLeft:(unsigned int)arg1 level:(unsigned int)arg2;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (BOOL)shouldShowInLockScreen;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)undimsScreen;

@end

