//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBDismissOnlyAlertItem;

@interface SBLockdownManager : NSObject
{
    int _state;
    BOOL _settingUpActivationState;
    BOOL _hasShownWaitingAlertThisSession;
    BOOL _hasShownMismatchedSIM;
    SBDismissOnlyAlertItem *_activatingAlertItem;
}

+ (id)sharedInstance;
- (id)init;
- (BOOL)_activationChecksEnabled;
- (BOOL)_hasEverRegistered;
- (void)_setHasEverRegistered:(BOOL)arg1;
- (BOOL)_isRegisteredToNetwork;
- (void)_setCurrentAlertItem:(id)arg1;
- (void)_postAlertsIfNeeded;
- (void)_activationChanged;
- (void)_serviceAvailabilityChanged:(id)arg1;
- (void)_setupActivationState;
- (BOOL)brickedDevice;
- (int)lockdownState;
- (void)dealloc;

@end

