//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface SBNowPlayingArtView : UIView
{
    UIImageView *_imageView;
    UIView *_reflection;
}

- (void)dealloc;
- (void)setAlbumArtImage:(id)arg1 maxSize:(float)arg2;
- (id)albumArtImage;
- (void)setReflectionVisible:(BOOL)arg1 withDuration:(float)arg2;

@end

