//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

@class SBPowerDownView;

@interface SBPowerDownController : SBAlert
{
    int _count;
    id _delegate;
    SBPowerDownView *_powerDownView;
    BOOL _isFront;
}

+ (id)sharedInstance;
- (void)dealloc;
- (float)autoLockTime;
- (BOOL)isOrderedFront;
- (void)orderFront;
- (void)orderOut;
- (id)powerDownView;
- (void)activate;
- (BOOL)deactivate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)alertDisplayWillBecomeVisible;
- (void)setDelegate:(id)arg1;
- (void)powerDown;
- (void)cancel;

@end

