//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIScroller;

@interface SBSIMToolkitTextAlertDisplay : SBSlidingAlertDisplay
{
    SBTextDisplayView *_contentView;
    UIScroller *_scroller;
}

+ (id)createTopBarForInstance:(id)arg1;
+ (id)createBottomBarForInstance:(id)arg1;
- (void)dealloc;
- (void)navigationBar:(id)arg1 buttonClicked:(int)arg2;
- (void)adjustScrollerFrame;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)showsDesktopImage;
- (void)setMiddleContentAlpha:(float)arg1;
- (void)displayDidTimeout;
- (id)alertText;
- (void)alertDisplayWillBecomeVisible;
- (void)accept:(id)arg1;
- (void)dismiss:(id)arg1;
- (void)dismiss;

@end

