//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSIMToolkitGetInputDisplay.h"

@interface SBSIMToolkitGetYesNoInputDisplay : SBSIMToolkitGetInputDisplay
{
}

+ (id)createBottomBarForInstance:(id)arg1;
- (void)yesPressed:(id)arg1;
- (void)noPressed:(id)arg1;

@end

