//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBSIMLockAlertItem, SBSIMLockEntryAlert;

@interface SBSIMLockManager : NSObject
{
    BOOL _isInitialUpdate;
    int _status;
    SBSIMLockAlertItem *_currentAlert;
    SBSIMLockEntryAlert *_lockEntryAlert;
}

+ (id)sharedInstance;
- (void)dealloc;
- (BOOL)_hopelesslyPUKLocked;
- (int)_CTToSBSIMStatus:(struct __CFString *)arg1;
- (int)_statusFromCT;
- (void)lockEntryAlertDismissed:(id)arg1;
- (void)alertItemDismissed:(id)arg1;
- (void)repopAlert;
- (void)attemptUnlock;
- (void)_updateToStatus:(int)arg1;
- (void)_tryToUpdateStatus;
- (void)_tearDownAlertAndUpdateStatus;
- (void)_updateSIMStatus:(struct __CFString *)arg1 withOptions:(struct __CFDictionary *)arg2;
- (int)pinLockAttemptsRemaining;
- (int)pukLockAttemptsRemaining;
- (void)_initialUpdate;
- (void)registerForAlerts;
- (int)status;

@end

