//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSIMToolkitTextAlertDisplay.h"

@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay
{
}

+ (id)createBottomBarForInstance:(id)arg1;
- (void)dismiss:(id)arg1;
- (id)_activeCalls;
- (void)dial:(id)arg1;
- (id)alertText;

@end

