//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

@class NSTimer;

@interface SBSIMToolkitAlert : SBAlert
{
    BOOL _needsResponse;
    NSTimer *_timeoutTimer;
}

+ (struct __CTServerConnection *)simToolkitServerConnection;
+ (BOOL)wantsNextUserEvent;
+ (void)userEventOccurred;
+ (void)setCurrentAlert:(id)arg1;
+ (id)currentAlert;
+ (void)test;
+ (void)_idleScreenShown:(id)arg1;
+ (void)_stopSTKMonitor;
+ (void)_startSTKMonitor;
+ (void)_restartMonitor;
+ (void)registerForAlerts;
- (void)setNeedsResponse:(BOOL)arg1;
- (BOOL)needsResponse;
- (void)sendResponse:(struct __CFString *)arg1 withString:(id)arg2;
- (void)sendResponse:(struct __CFString *)arg1 withBool:(BOOL)arg2;
- (void)sendResponse:(struct __CFString *)arg1;
- (void)_stopTone:(id)arg1;
- (BOOL)sendResponseUponDisplay;
- (void)dealloc;
- (void)_playTone:(struct __CFString *)arg1 forDuration:(float)arg2;
- (struct __CFString *)toolkitAlertType;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)clearTimeoutTimer;
- (BOOL)_delayEnabled;
- (void)restartTimeoutTimer:(float)arg1;
- (void)startTimeoutTimerIfNecessary;
- (void)displayDidTimeout;

@end

