//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@interface SBSMSAlertItem : SBAlertItem
{
    struct __CTSMSMessage *_message;
}

+ (void)prefsChanged;
- (void)dealloc;
- (void)_tag;
- (void)_untag;
- (void)_deactivateAllTaggedSMSAlertItems;
- (void)willActivate;
- (void)didActivate;
- (void)didDeactivate:(BOOL)arg1;
- (void)setMessage:(struct __CTSMSMessage *)arg1;
- (void)_playMessageReceived;
- (void)willPresentAlertSheet:(id)arg1;
- (id)address;
- (id)messageText;
- (void)reply;
- (void)dismiss;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (void)performUnlockAction;
- (BOOL)_showSMSPreviewWithPasscodeEnabled;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (BOOL)willShowInAwayItems;
- (BOOL)shouldShowInEmergencyCall;

@end

