//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBSoundPreferences : NSObject
{
}

+ (void)userDefaultsDidChanged:(id)arg1;
+ (id)calendarAlarmPath;
+ (id)ringtonePath;
+ (BOOL)playLockSound;
+ (id)vibratePattern;
+ (BOOL)vibrateWhenRinging;
+ (BOOL)vibrateWhenSilent;
+ (BOOL)shouldVibrateForCurrentRingerState;

@end

