//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class UIView;

@interface SBStatusWindow : UIWindow
{
    int _orientation;
    UIView *_holderView;
}

+ (struct CGRect)constrainFrameToScreen:(struct CGRect)arg1;
- (BOOL)isOpaque;
- (id)initWithFrame:(struct CGRect)arg1;
- (int)orientation;
- (void)setOrientation:(int)arg1;
- (id)holderView;

@end

