//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarContentView.h"

@interface SBStatusBarBatteryView : SBStatusBarContentView
{
    int _batteryCapacity;
    BOOL _batteryCharging;
    BOOL _isOnAC;
}

- (void)updateBattery;
- (void)_batteryStatusChanged:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)setBatteryCapacity:(int)arg1 andCharging:(BOOL)arg2 isOnAC:(BOOL)arg3;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;

@end

