//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarContentView.h"

@class UIImage, UIImageView;

@interface SBStatusBarBluetoothView : SBStatusBarContentView
{
    UIImage *_icon;
    BOOL _animating;
    UIImageView *_activeView;
    UIImageView *_baseLayer;
    BOOL _isStarted;
}

+ (void)initialize;
- (id)icon;
- (id)init;
- (int)_effectiveMode;
- (void)_setupActiveView;
- (int)btStatus;
- (void)_btStatusChanged:(id)arg1;
- (void)_btDeviceConnected;
- (void)_btConnectionStatusChanged:(id)arg1;
- (void)_btDeviceDisconnected:(id)arg1;
- (void)animationDidStop:(id)arg1;
- (void)_start;
- (void)_btPowerPrefChanged:(id)arg1;
- (void)start;
- (void)stop;
- (void)dealloc;

@end

