//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarContentView.h"

@class NSString;

@interface SBStatusBarNoServiceView : SBStatusBarContentView
{
    NSString *_errorString;
}

+ (id)displayStringForSIMStatus:(id)arg1;
+ (id)displayStringForRegistrationStatus:(int)arg1;
- (id)initWithErrorString:(id)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (struct __GSFont *)textFont;

@end

