//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBStatusBarContentsView;

@interface SBStatusBarContentView : UIView
{
    SBStatusBarContentsView *_contentsView;
    int _mode;
}

- (id)initWithContentsView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setMode:(int)arg1;
- (int)effectiveModeForImages;
- (void)start;
- (void)stop;
- (struct __GSFont *)textFont;
- (void)drawText:(id)arg1 atPoint:(struct CGPoint)arg2 forWidth:(float)arg3 ellipsis:(int)arg4;
- (void)enableShadow;

@end

