//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarContentView.h"

@interface SBStatusBarSignalView : SBStatusBarContentView
{
    int _dBm;
    int _signalStrength;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (int)barsForRawDBM:(float)arg1;
- (void)setSignalStrength:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;

@end

