//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarContentView.h"

@interface SBStatusBarAirPortView : SBStatusBarContentView
{
    int _signalStrength;
    unsigned int _showsAirPort:1;
    unsigned int _isPolling:1;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)setAirPortStrength:(int)arg1;
- (void)setShowsAirPort:(BOOL)arg1;
- (void)dataConnectionTypeChanged;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;

@end

