//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStatusBarContentView.h"

@class SBStatusBarOperatorNameView, UIImage;

@interface SBStatusBarCarrierView : SBStatusBarContentView
{
    UIImage *_operatorIcon;
    SBStatusBarOperatorNameView *_operatorNameView;
    BOOL _operatorNameIsLooping;
}

- (id)init;
- (void)dealloc;
- (void)start;
- (void)stop;
- (void)clearLastOperatorNameLooped;
- (void)loopOperatorNameToBeginning:(id)arg1 didFinish:(id)arg2;
- (void)loopOperatorNameToEnd;
- (void)finishedLoopingOperatorName:(id)arg1 didFinish:(id)arg2;
- (void)startOperatorNameLooping:(id)arg1;
- (void)loopIfNecessary;
- (void)setOperatorName:(id)arg1;
- (BOOL)_operatorName:(id)arg1 isEqualToName:(id)arg2;
- (id)operatorIconForName:(id)arg1;
- (struct CGSize)defaultSize;
- (void)operatorNameChanged;

@end

