//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class SBStatusBarContentsView, SBStatusBarController, SBStatusBarInCallView, SBStatusWindow, UIView;

@interface SBStatusBar : UIControl
{
    int _mode;
    int _orientation;
    SBStatusBarController *_controller;
    SBStatusBarContentsView *_contentsView;
    SBStatusBarInCallView *_inCallView;
    SBStatusWindow *_statusWindow;
    UIView *_airplaneView;
    UIView *_glowView;
    UIView *_glassView;
    UIView *_dimmerView;
    unsigned int _animate:1;
    unsigned int _animating:1;
    unsigned int _isPressed:1;
    unsigned int _airplaneMode:1;
}

- (id)initWithStatusBarController:(id)arg1 mode:(int)arg2 orientation:(int)arg3;
- (void)setStatusWindow:(id)arg1;
- (id)statusWindow;
- (void)dealloc;
- (int)mode;
- (int)orientation;
- (id)contentsView;
- (id)airplaneView;
- (void)drawRect:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)start;
- (void)stop;
- (void)showDimmerOverlay:(BOOL)arg1;
- (void)startGlowAnimation;
- (void)stopGlowAnimation;
- (void)setAirplaneModeIsEnabled:(BOOL)arg1 animate:(BOOL)arg2;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)beginTrackingAt:(struct CGPoint)arg1 withEvent:(struct __GSEvent *)arg2;
- (BOOL)isDimmed;
- (void)statusBarClicked;
- (void)mouseDown:(struct __GSEvent *)arg1;
- (void)mouseDragged:(struct __GSEvent *)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;

@end

