//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBStatusBarAirPortView, SBStatusBarBatteryView, SBStatusBarBluetoothView, SBStatusBarCarrierView, SBStatusBarController, SBStatusBarIndicatorsView, SBStatusBarNoServiceView, SBStatusBarProgressView, SBStatusBarSignalView, SBStatusBarTimeView;

@interface SBStatusBarContentsView : UIView
{
    SBStatusBarController *_controller;
    int _mode;
    BOOL _dimmed;
    UIView *_lockIconView;
    SBStatusBarTimeView *_timeView;
    SBStatusBarBatteryView *_batteryView;
    SBStatusBarSignalView *_signalView;
    SBStatusBarCarrierView *_carrierView;
    SBStatusBarIndicatorsView *_indicatorsView;
    SBStatusBarAirPortView *_airPortView;
    SBStatusBarNoServiceView *_noServiceView;
    SBStatusBarBluetoothView *_bluetoothView;
    SBStatusBarProgressView *_progressView;
}

+ (float)contentAlphaForMode:(int)arg1;
- (id)initWithStatusBarController:(id)arg1 mode:(int)arg2;
- (void)dealloc;
- (void)buildContentViews;
- (void)updateContentViewsAlpha;
- (void)reflowContentViews;
- (void)stop;
- (void)start;
- (void)stopClock;
- (void)startClock;
- (void)updateClockFormat;
- (void)setShowsService:(BOOL)arg1 SIMStatus:(id)arg2;
- (void)significantTimeChange;
- (void)signalFormatChanged;
- (void)customTextChanged;
- (void)progressChanged;
- (void)cloakChanged;
- (void)setAirPortStrength:(int)arg1;
- (void)setShowsAirPort:(BOOL)arg1 animate:(BOOL)arg2;
- (void)indicatorsChanged;
- (void)setIsInAirplaneMode:(BOOL)arg1 animate:(BOOL)arg2;
- (void)loopCarrierNameIfNecessary;

@end

