//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SBTelephonyManager : NSObject
{
    NSString *_operatorName;
}

+ (id)sharedTelephonyManager;
- (id)init;
- (struct __CTServerConnection *)_serverConnection;
- (void)updateTTYIndicator;
- (double)inCallDuration;
- (void)updateSpringBoard;
- (void)updateAirplaneMode;
- (void)updateCalls;
- (void)_updateState;
- (void)updateLocale;
- (void)_whackGain:(id)arg1;
- (id)displayForOutgoingCallURL:(id)arg1;
- (void)_mainThreadDaemonRestart:(struct __CFDictionary *)arg1;
- (void)_delayedAudioResume;
- (long long)getRowIDOfLastCallInsert;
- (id)allMissedCallsAfterRowID:(long long)arg1;
- (long long)getRowIDOfLastSMSInsert;
- (id)allUnreadSMSAfterRowID:(long long)arg1;
- (void)markMessageAsRead:(struct __CTSMSMessage *)arg1;
- (void)updateSMSBadges;
- (int)callCount;
- (BOOL)activeCallExists;
- (BOOL)heldCallExists;
- (BOOL)incomingCallExists;
- (BOOL)outgoingCallExists;
- (BOOL)inCallUsingReceiver;
- (BOOL)inCall;
- (void)disconnectIncomingCall;
- (void)answerIncomingCall;
- (void)answerIncomingCallEndingOthers;
- (void)swapCalls;
- (void)disconnectAllCalls;
- (void)disconnectCall;
- (void)disconnectCallAndActivateHeld;
- (void)unmute;
- (void)dumpBasebandState:(id)arg1;
- (void)powerOffRadio;
- (int)dataConnectionType;
- (BOOL)EDGEIsAvailable;
- (BOOL)isUsingDataConnection;
- (BOOL)isUsingWiFiConnection;
- (void)copyICCID:(id *)arg1 IMEI:(id *)arg2;
- (void)configureForTTY:(BOOL)arg1;
- (BOOL)shouldPromptForTTY;
- (id)ttyTitle;
- (void)_resetCTMMode;
- (void)_headphoneChanged:(id)arg1;
- (void)_setRegistrationStatus:(int)arg1;
- (void)_updateRegistrationNow;
- (void)_cancelFakeService;
- (void)_startFakeServiceIfNecessary;
- (void)_stopFakeService;
- (void)_reallySetOperatorName:(id)arg1;
- (void)setOperatorName:(id)arg1;
- (id)operatorName;
- (int)registrationStatus;
- (void)checkForRegistrationSoon;
- (id)SIMStatus;

@end

