//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSlidingAlertDisplay.h"

@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)createTopBarForInstance:(id)arg1;
+ (id)createBottomBarForInstance:(id)arg1;
- (id)initWithSize:(struct CGSize)arg1;
- (void)_makeCall;
- (void)_chooseVoiceMode:(id)arg1;
- (void)_chooseTTYMode:(id)arg1;
- (void)_ignore:(id)arg1;

@end

