//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBApplication, SBButtonBar, SBContentLayer, SBIconList, SBZoomView, UIWindow;

@interface SBUIController : NSObject
{
    UIWindow *_window;
    SBIconList *_iconList;
    SBButtonBar *_buttonBar;
    SBContentLayer *_contentLayer;
    SBZoomView *_zoomLayer;
    SBApplication *_launchedApp;
    int _launchState;
    BOOL _lastVolumeDownToControl;
    BOOL _shouldAutoLock;
    int _batteryCapacity;
    BOOL _isBatteryCharging;
    BOOL _isOnAC;
    BOOL _cancelingLaunch;
    BOOL _resetBatteryUsage;
    int _batteryLoggingStartCapacity;
    unsigned char _headsetBatteryCapacity;
    BOOL _isHeadsetCharging;
    BOOL _isHeadsetDocked;
}

+ (int)displayedLevelForBatteryLevel:(int)arg1;
+ (int)displayedLevelForBatteryStatusBarLevel:(int)arg1;
+ (id)sharedInstance;
- (void)_indicateConnectedToPower;
- (void)dealloc;
- (id)init;
- (float)calculateStartupTime;
- (id)getVMstats;
- (void)logStartupData;
- (void)finishLaunching;
- (void)systemControllerRouteChanged:(id)arg1;
- (BOOL)shouldDisconnectCallsOnLockPress;
- (void)lock:(BOOL)arg1;
- (void)lock;
- (int)launchState;
- (void)clearZoomLayer;
- (void)setState:(int)arg1;
- (id)contentView;
- (id)statusBarWindow;
- (id)window;
- (id)buttonBar;
- (id)iconList;
- (void)showZoomLayerForApp:(id)arg1;
- (void)stopAllAnimations;
- (void)hideIconListAndBar:(BOOL)arg1;
- (void)restoreIconList:(BOOL)arg1 force:(BOOL)arg2;
- (void)stopRestoringIconList;
- (void)showButtonBar:(BOOL)arg1 animate:(BOOL)arg2 action:(SEL)arg3 delegate:(id)arg4;
- (void)quitTopApplication;
- (struct CGAffineTransform)_initialStatusBarTransformForScale:(float)arg1;
- (void)animateLaunchOfApplication:(id)arg1 afterDelay:(double)arg2 startingAtTime:(double)arg3 forDuration:(double)arg4 includingIconsAndButtonBar:(BOOL)arg5 initialZoomScale:(float)arg6 fadeInZoom:(BOOL)arg7;
- (void)cancelLaunchOfApplication:(id)arg1 duration:(double)arg2;
- (void)animateLaunchOfApplication:(id)arg1;
- (void)animateLaunchIcon:(id)arg1;
- (double)animateLaunchForReturnToLastApp:(id)arg1;
- (void)finishedFadingInButtonBar;
- (void)showZoomLayerAnimationDidStop:(id)arg1 finished:(id)arg2;
- (void)cancelLaunchAnimationDidStop:(id)arg1 finished:(id)arg2;
- (void)clickedMenuButton;
- (void)completeAlertDisplay;
- (void)wakeUp:(id)arg1;
- (void)handleVolumeEvent:(struct __GSEvent *)arg1;
- (void)applicationExited:(id)arg1;
- (void)applicationSuspended:(id)arg1;
- (int)batteryCapacity;
- (BOOL)isBatteryCharging;
- (BOOL)isOnAC;
- (void)ACPowerChanged;
- (void)noteStatusBarHeightChanged:(float)arg1 duration:(double)arg2;
- (BOOL)isHeadsetDocked;
- (BOOL)isHeadsetBatteryCharging;
- (unsigned char)headsetBatteryCapacity;
- (void)handleAccessoryAvailabilityChange:(struct __GSEvent *)arg1 removal:(BOOL)arg2;
- (void)handleAccessoryEvent:(struct __GSEvent *)arg1;

@end

