//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSString;

@interface SBUserNotificationAlert : SBAlertItem
{
    unsigned int _replyPort;
    int _token;
    int _timeout;
    unsigned int _requestFlags;
    NSString *_alertHeader;
    NSString *_alertMessage;
    NSString *_defaultButtonTitle;
    NSString *_alternateButtonTitle;
    id _textFieldTitles;
    id _textFieldValues;
    id _keyboardTypes;
    double _creationTime;
    unsigned int _replyFlags;
    unsigned int _cancel:1;
    unsigned int _isActivated:1;
    unsigned int _aboveLock:1;
    unsigned int _reserved:29;
}

- (id)initWithMessage:(id)arg1 replyPort:(unsigned int)arg2 requestFlags:(int)arg3;
- (void)dealloc;
- (id)alertSheet;
- (int)token;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)wakeup;
- (void)cancel;
- (void)_sendResponse:(int)arg1;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (void)didDeactivate:(BOOL)arg1;

@end

