//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSString;

@interface SBWiFiPasswordAlertItem : SBAlertItem
{
    id _delegate;
    NSString *_name;
}

- (id)initWithNetworkName:(id)arg1;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)dismiss;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (void)returnKeyPressed:(id)arg1;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;

@end

