//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock;

@interface SBWiFiManager : NSObject
{
    struct _Apple80211 *_wireless;
    BOOL _busy;
    BOOL _joining;
    BOOL _cancel;
    NSLock *_lock;
    id _delegate;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)scan;
- (BOOL)busy;
- (BOOL)joining;
- (void)dismissAlerts;
- (void)_scanThread;
- (void)_scanComplete:(id)arg1;
- (void)_joinNetworkThread:(id)arg1;
- (void)_joinNetwork:(id)arg1;
- (void)_joinComplete:(id)arg1;
- (void)_SBAirPortUpdateTimer;
- (void)_SBAirPortPowerChanged;
- (void)_SBAirPortConfigurationChanged;
- (void)joinSecureNetwork:(id)arg1 password:(id)arg2;
- (void)joinNetwork:(id)arg1;

@end

