//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface SBWiFiSignalStrength : UIImageView
{
    int _bars;
    int _rawStrength;
    BOOL _hilited;
    BOOL _selected;
    BOOL _secure;
    BOOL _joining;
    UIImageView *_icon;
}

+ (void)hideSpinner;
- (void)setSpinnerHilited:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)dealloc;
- (BOOL)joining;
- (void)setJoining:(BOOL)arg1;
- (void)updateStrength:(id)arg1;
- (BOOL)selected;
- (void)hide;
- (void)setSelected:(BOOL)arg1;
- (BOOL)hilited;
- (void)setHilited:(BOOL)arg1;
- (BOOL)secure;
- (void)setSecure:(BOOL)arg1;
- (void)updateImage;

@end

