//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertSheetTableCell.h"

@interface SBWiFiCell : UIAlertSheetTableCell
{
    id _userInfo;
}

- (id)initWithFrame:(struct CGRect)arg1 networkDictionary:(id)arg2;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)layoutSubviews;
- (void)updateHighlightColors;

@end

