//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSDictionary, NSMutableArray, NSString, NSTimer, UITable;

@interface SBWiFiAlertItem : SBAlertItem
{
    NSMutableArray *_networks;
    NSTimer *_scanTimer;
    UITable *_table;
    struct CGSize _size;
    int _joinRow;
    NSString *_password;
    NSDictionary *_joinDict;
    SBAlertItem *_childAlert;
    BOOL _selectingRow;
    BOOL _storedPassword;
}

- (void)scan;
- (id)init;
- (int)_joinRow;
- (void)setNetworks:(id)arg1;
- (void)setChildAlert:(id)arg1;
- (id)insertionsForNewNetworks:(id)arg1;
- (id)deletionSetForLostNetworks:(id)arg1 originalNetworks:(id)arg2;
- (void)wifiManager:(id)arg1 scanCompleted:(id)arg2;
- (void)_enableTable;
- (void)dismiss;
- (void)willDeactivate:(BOOL)arg1;
- (void)willActivate;
- (void)wifiManager:(id)arg1 joinCompleted:(int)arg2;
- (void)didPresentAlertSheet:(id)arg1;
- (void)passwordEntered:(id)arg1;
- (void)dealloc;
- (void)alertSheet:(id)arg1 buttonClicked:(int)arg2;
- (BOOL)allowMenuButtonDismissal;
- (void)performUnlockAction;
- (int)numberOfRowsInTable:(id)arg1;
- (id)table:(id)arg1 cellForRow:(int)arg2 column:(id)arg3;
- (void)tableSelectionDidChange:(id)arg1;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (BOOL)dismissOnLock;
- (void)didDeactivate:(BOOL)arg1;

@end

