//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SpringBoard.h"

@interface SpringBoard (SBApplicationTesting)
- (id)_pathForTestOptions:(id)arg1;
- (BOOL)runTest:(id)arg1 options:(id)arg2;
- (void)startLaunchTestNamed:(id)arg1 options:(id)arg2;
- (void)startResumeTestNamed:(id)arg1 options:(id)arg2;
- (void)anotherApplicationFinishedLaunching:(struct __GSEvent *)arg1;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2;
@end

